# Generated by Django 4.1.3 on 2022-12-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0007_country_alter_address_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="published_countries",
            field=models.ManyToManyField(to="book_outlet.country"),
        ),
    ]
